# Generated by Django 5.0.3 on 2024-04-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworkflow',
            name='status',
            field=models.CharField(choices=[('To-do', 'to-do'), ('In-Progress', 'in-progress'), ('Complete', 'complete')], default='in-progress', max_length=11),
        ),
    ]
