# Generated by Django 5.0.3 on 2024-04-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_projectworkflow_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectworkflow',
            old_name='name',
            new_name='title',
        ),
    ]
