# Generated by Django 5.0.3 on 2024-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_rename_name_projectworkflow_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
